"""Add department unique constraints

Revision ID: 33f071bee724
Revises: 3c4e608330e9
Create Date: 2026-07-09 09:34:00.928581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f071bee724'
down_revision = '3c4e608330e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_department_code_per_faculty', ['faculty_id', 'code'])
        batch_op.create_unique_constraint('uq_department_name_per_faculty', ['faculty_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_department_name_per_faculty', type_='unique')
        batch_op.drop_constraint('uq_department_code_per_faculty', type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
