"""Create Student model

Revision ID: 550b537837d4
Revises: 4b97cbc746a8
Create Date: 2026-07-19 17:27:25.488374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550b537837d4'
down_revision = '4b97cbc746a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=30), nullable=False),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('is_voter', sa.Boolean(), nullable=False),
    sa.Column('is_candidate_eligible', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_admission_year'), ['admission_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))
        batch_op.drop_index(batch_op.f('ix_students_email'))
        batch_op.drop_index(batch_op.f('ix_students_admission_year'))

    op.drop_table('students')
    # ### end Alembic commands ###
