"""Add academic_year to elections

Revision ID: d5a602606832
Revises: 7814f92a1c80
Create Date: 2026-07-24 17:51:42.074971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a602606832'
down_revision = '7814f92a1c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.String(length=20), nullable=False))
        batch_op.alter_column('election_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('election_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###
