from .user import User
from .audit_log import AuditLog
from app.models.faculty import Faculty
from app.models.department import Department
from app.models.academic_year import AcademicYear
from app.models.semester import Semester
from app.models.program import Program
from app.models.student import Student
from app.models.election import Election